In [1]:
import pandas as pd

In [2]:
wine = pd.read_csv('winequality-red.csv')

In [3]:
wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [4]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [5]:
wine.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [11]:
wine_quality = wine['quality']
wine_data = wine.drop('quality', axis=1)

In [12]:
wine_quality

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [13]:
wine_data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

# 선형 회귀

In [14]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(wine_data, wine_quality)

LinearRegression()

In [15]:
from sklearn.metrics import mean_squared_error
import numpy as np

wine_predictions = lin_reg.predict(wine_data)
lin_mse = mean_squared_error(wine_quality, wine_predictions)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

0.6455750670692045

In [16]:
from sklearn.metrics import mean_absolute_error

lin_mae = mean_absolute_error(wine_quality, wine_predictions)
lin_mae

0.500489963564488

In [21]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor(random_state=42)
tree_reg.fit(wine_data, wine_quality)

DecisionTreeRegressor(random_state=42)

In [22]:
wine_predictions = tree_reg.predict(wine_data)
tree_mse = mean_squared_error(wine_quality, wine_predictions)
tree_rmse = np.sqrt(tree_mse)
tree_rmse

0.0

# 교차 검증

In [23]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(tree_reg, wine_data, wine_quality, 
                         scoring="neg_mean_squared_error", cv=10)
tree_rmse_scores = np.sqrt(-scores)

In [24]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())
    
display_scores(tree_rmse_scores)

Scores: [0.81394103 0.78660664 0.92870878 0.88388348 0.95197164 0.95524866
 1.00933146 0.92195445 1.         0.83553169]
Mean: 0.9087177819592572
Standard deviation: 0.07275516136855807

In [25]:
lin_scores = cross_val_score(lin_reg, wine_data, wine_quality, 
                             scoring="neg_mean_squared_error", cv=10)
lin_rmse_scores = np.sqrt(-lin_scores)
display_scores(lin_rmse_scores)

Scores: [0.68624812 0.63247034 0.6850469  0.6570567  0.61372354 0.723601
 0.63281973 0.65532399 0.60149415 0.69851308]
Mean: 0.6586297547378719
Standard deviation: 0.03730616844468721

In [46]:
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor(n_estimators=100,random_state=42)
forest_reg.fit(wine_data, wine_quality)

RandomForestRegressor(random_state=42)

In [47]:
wine_predictions = forest_reg.predict(wine_data)
forest_mse = mean_squared_error(wine_quality, wine_predictions)
forest_rmse = np.sqrt(forest_mse)
forest_rmse

0.21261424107922205

In [48]:
from sklearn.model_selection import cross_val_score

forest_scores = cross_val_score(forest_reg, wine_data, wine_quality,
                                scoring="neg_mean_squared_error", cv=10)
forest_rmse_scores = np.sqrt(-forest_scores)
display_scores(forest_rmse_scores)

Scores: [0.61371614 0.58156631 0.68472075 0.66384722 0.5649209  0.72317443
 0.66583876 0.65855239 0.61977667 0.70264281]
Mean: 0.6478756369545334
Standard deviation: 0.04894232181514159

# citric acid 제거

In [62]:
wine_1 = wine_data.drop(['citric acid'], axis=1)

In [64]:
wine_1

,fixed acidity,volatile acidity,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.700,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1596,6.3,0.510,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1597,5.9,0.645,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

In [65]:
wine_quality

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [69]:
forest_reg = RandomForestRegressor(n_estimators=100,random_state=42)
forest_reg.fit(wine_1, wine_quality)

RandomForestRegressor(random_state=42)

In [70]:
wine_predictions = forest_reg.predict(wine_1)
forest_mse = mean_squared_error(wine_quality, wine_predictions)
forest_rmse = np.sqrt(forest_mse)
forest_rmse

0.21315624490139337

In [71]:
from sklearn.model_selection import cross_val_score

forest_scores = cross_val_score(forest_reg, wine_1, wine_quality,
                                scoring="neg_mean_squared_error", cv=10)
forest_rmse_scores = np.sqrt(-forest_scores)
display_scores(forest_rmse_scores)

Scores: [0.61905018 0.59001006 0.68796621 0.66255613 0.56385448 0.7295084
 0.66926032 0.66105266 0.61848504 0.70553294]
Mean: 0.6507276422902682
Standard deviation: 0.049460423727698814

# residual sugar, free sulfur ~, pH 제거

In [72]:
wine_data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

In [73]:
wine_2 = wine_data.drop(['residual sugar', 'free sulfur dioxide'], axis=1)

In [74]:
wine_2

,fixed acidity,volatile acidity,citric acid,chlorides,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,0.00,0.076,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,0.098,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,0.092,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,0.075,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.700,0.00,0.076,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,0.090,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,0.062,51.0,0.99512,3.52,0.76,11.2
1596,6.3,0.510,0.13,0.076,40.0,0.99574,3.42,0.75,11.0
1597,5.9,0.645,0.12,0.075,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,0.067,42.0,0.99549,3.39,0.66,11.0

In [75]:
forest_reg = RandomForestRegressor(n_estimators=100, random_state=42)
forest_reg.fit(wine_2, wine_quality)

RandomForestRegressor(random_state=42)

In [76]:
wine_predictions = forest_reg.predict(wine_2)
forest_mse = mean_squared_error(wine_quality, wine_predictions)
forest_rmse = np.sqrt(forest_mse)
forest_rmse

0.21143454153317956

In [77]:
from sklearn.model_selection import cross_val_score

forest_scores = cross_val_score(forest_reg, wine_2, wine_quality,
                                scoring="neg_mean_squared_error", cv=10)
forest_rmse_scores = np.sqrt(-forest_scores)
display_scores(forest_rmse_scores)

Scores: [0.61645154 0.58162273 0.68406049 0.67597707 0.58123521 0.73422663
 0.6703017  0.65903243 0.60944186 0.70504605]
Mean: 0.6517395723187617
Standard deviation: 0.049595474435169304

# SVM 회귀

In [79]:
X = wine_data
y = wine_quality

In [87]:
from sklearn.svm import LinearSVR

SVM_reg = LinearSVR(epsilon=1.5, random_state=42)
SVM_reg.fit(X, y)

C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "

LinearSVR(epsilon=1.5, random_state=42)

In [88]:
wine_predictions = svm_reg.predict(X)
SVM_mse = mean_squared_error(y, wine_predictions)
SVM_rmse = np.sqrt(SVM_mse)
SVM_rmse

0.7180641089120892

In [89]:
from sklearn.model_selection import cross_val_score

SVM_scores = cross_val_score(SVM_reg, X, y,
                                scoring="neg_mean_squared_error", cv=10)
SVM_rmse_scores = np.sqrt(-SVM_scores)
display_scores(SVM_rmse_scores)

C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "

Scores: [0.79726579 0.73923994 0.80334404 0.81020093 0.65547741 0.97857026
 0.70041006 0.68973787 0.70040056 0.76619804]
Mean: 0.7640844905186694
Standard deviation: 0.08765152221167677

C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "

# 세부 튜닝

In [94]:
from sklearn.model_selection import GridSearchCV

param_grid = [
    # try 12 (3×4) combinations of hyperparameters
    {'n_estimators': [3, 10, 30], 'max_features': [2, 4, 6, 8]},
    # then try 6 (2×3) combinations with bootstrap set as False
    {'bootstrap': [False], 'n_estimators': [3, 10], 'max_features': [2, 3, 4]},
  ]

forest_reg = RandomForestRegressor(random_state=42)
# train across 5 folds, that's a total of (12+6)*5=90 rounds of training 
grid_search = GridSearchCV(forest_reg, param_grid, cv=5,
                           scoring='neg_mean_squared_error',
                           return_train_score=True)
grid_search.fit(wine_data, wine_quality)

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42),
             param_grid=[{'max_features': [2, 4, 6, 8],
                          'n_estimators': [3, 10, 30]},
                         {'bootstrap': [False], 'max_features': [2, 3, 4],
                          'n_estimators': [3, 10]}],
             return_train_score=True, scoring='neg_mean_squared_error')

In [95]:
grid_search.best_params_

{'max_features': 2, 'n_estimators': 30}

In [96]:
grid_search.best_estimator_

RandomForestRegressor(max_features=2, n_estimators=30, random_state=42)

In [97]:
cvres = grid_search.cv_results_
for mean_score, params in zip(cvres["mean_test_score"], cvres["params"]):
    print(np.sqrt(-mean_score), params)

0.7574831317460692 {'max_features': 2, 'n_estimators': 3}
0.6851906354413724 {'max_features': 2, 'n_estimators': 10}
0.652132996179213 {'max_features': 2, 'n_estimators': 30}
0.7513897781751369 {'max_features': 4, 'n_estimators': 3}
0.675558082307164 {'max_features': 4, 'n_estimators': 10}
0.6576434208202053 {'max_features': 4, 'n_estimators': 30}
0.7513781892039618 {'max_features': 6, 'n_estimators': 3}
0.6795277005156045 {'max_features': 6, 'n_estimators': 10}
0.6541040060106695 {'max_features': 6, 'n_estimators': 30}
0.7528893317563466 {'max_features': 8, 'n_estimators': 3}
0.6795728074510922 {'max_features': 8, 'n_estimators': 10}
0.6571805907095053 {'max_features': 8, 'n_estimators': 30}
0.777506312405707 {'bootstrap': False, 'max_features': 2, 'n_estimators': 3}
0.6871680589365097 {'bootstrap': False, 'max_features': 2, 'n_estimators': 10}
0.7628161620202858 {'bootstrap': False, 'max_features': 3, 'n_estimators': 3}
0.6890443469537831 {'bootstrap': False, 'max_features': 3, 'n_estimators': 10}
0.7693093678865076 {'bootstrap': False, 'max_features': 4, 'n_estimators': 3}
0.6952341963499024 {'bootstrap': False, 'max_features': 4, 'n_estimators': 10}

In [98]:
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_features,param_n_estimators,param_bootstrap,params,split0_test_score,split1_test_score,...,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
0,0.008173,0.000749,0.001607,0.000498,2,3,NaN,"{'max_features': 2, 'n_estimators': 3}",-0.429514,-0.664931,...,-0.573781,0.078356,15,-0.109982,-0.105986,-0.109982,-0.103640,-0.107552,-0.107428,0.002429
1,0.019356,0.001477,0.002392,0.000490,2,10,NaN,"{'max_features': 2, 'n_estimators': 10}",-0.414062,-0.527062,...,-0.469486,0.037283,8,-0.060868,-0.059234,-0.060172,-0.058444,-0.058555,-0.059454,0.000937
2,0.053653,0.003523,0.003189,0.000398,2,30,NaN,"{'max_features': 2, 'n_estimators': 30}",-0.382139,-0.455163,...,-0.425277,0.024627,1,-0.053297,-0.050731,-0.051615,-0.049098,-0.048203,-0.050589,0.001807
3,0.009166,0.000751,0.001999,0.000017,4,3,NaN,"{'max_features': 4, 'n_estimators': 3}",-0.494792,-0.577778,...,-0.564587,0.048329,13,-0.101034,-0.101468,-0.113022,-0.117019,-0.097917,-0.106092,0.007500
4,0.024736,0.000735,0.001986,0.000014,4,10,NaN,"{'max_features': 4, 'n_estimators': 10}",-0.410781,-0.486844,...,-0.456379,0.026809,5,-0.059077,-0.061955,-0.057842,-0.062181,-0.060453,-0.060302,0.001664
5,0.068816,0.003134,0.003789,0.000747,4,30,NaN,"{'max_features': 4, 'n_estimators': 30}",-0.395715,-0.451497,...,-0.432495,0.020477,4,-0.051888,-0.049658,-0.050024,-0.051026,-0.051238,-0.050767,0.000816
6,0.011975,0.001991,0.001987,0.000631,6,3,NaN,"{'max_features': 6, 'n_estimators': 3}",-0.484028,-0.568750,...,-0.564569,0.053677,12,-0.101729,-0.101555,-0.104335,-0.100599,-0.109288,-0.103501,0.003148
7,0.032114,0.001175,0.002394,0.000489,6,10,NaN,"{'max_features': 6, 'n_estimators': 10}",-0.406281,-0.469594,...,-0.461758,0.031184,6,-0.060125,-0.058436,-0.060203,-0.057342,-0.060352,-0.059292,0.001199
8,0.088148,0.002235,0.003780,0.000729,6,30,NaN,"{'max_features': 6, 'n_estimators': 30}",-0.394889,-0.428222,...,-0.427852,0.017008,2,-0.051069,-0.049634,-0.051805,-0.049130,-0.051465,-0.050621,0.001050
9,0.011969,0.000630,0.001595,0.000489,8,3,NaN,"{'max_features': 8, 'n_estimators': 3}",-0.472917,-0.545139,...,-0.566842,0.053070,14,-0.090435,-0.113370,-0.119103,-0.112067,-0.100000,-0.106995,0.010355
10,0.035907,0.001646,0.002591,0.000490,8,10,NaN,"{'max_features': 8, 'n_estimators': 10}",-0.408500,-0.461406,...,-0.461819,0.027789,7,-0.056716,-0.059429,-0.058006,-0.060094,-0.059594,-0.058768,0.001238
11,0.105327,0.001633,0.004374,0.000469,8,30,NaN,"{'max_features': 8, 'n_estimators': 30}",-0.386878,-0.435361,...,-0.431886,0.022999,3,-0.048961,-0.049897,-0.050639,-0.049999,-0.052455,-0.050390,0.001163
12,0.007777,0.000380,0.001401,0.000479,2,3,False,"{'bootstrap': False, 'max_features': 2, 'n_est...",-0.578472,-0.597222,...,-0.604516,0.037050,18,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000,0.000000
13,0.021143,0.000399,0.001986,0.000015,2,10,False,"{'bootstrap': False, 'max_features': 2, 'n_est...",-0.422594,-0.490281,...,-0.472200,0.027416,9,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000,0.000000
14,0.008965,0.000016,0.001798,0.000400,3,3,False,"{'bootstrap': False, 'max_features': 3, 'n_est...",-0.561806,-0.575347,...,-0.581888,0.054921,16,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000,0.000000
15,0.025953,0.000642,0.002195,0.000399,3,10,False,"{'bootstrap': False, 'max_features': 3, 'n_est...",-0.441281,-0.505469,...,-0.474782,0.032381,10,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000,0.000000
16,0.009966,0.000013,0.001803,0.000402,4,3,False,"{'bootstrap': False, 'max_features': 4, 'n_est...",-0.465278,-0.597569,...,-0.591837,0.068883,17,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000,0.000000
17,0.030118,0.000744,0.002401,0.000482,4,10,False,"{'bootstrap': False, 'max_features': 4, 'n_est...",-0.420875,-0.498062,...,-0.483351,0.036385,11,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000,0.000000

In [99]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_distribs = {
        'n_estimators': randint(low=1, high=200),
        'max_features': randint(low=1, high=8),
    }

forest_reg = RandomForestRegressor(random_state=42)
rnd_search = RandomizedSearchCV(forest_reg, param_distributions=param_distribs,
                                n_iter=10, cv=5, scoring='neg_mean_squared_error', random_state=42)
rnd_search.fit(wine_data, wine_quality)

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42),
                   param_distributions={'max_features': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000012D6B66C550>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000012D69370EB0>},
                   random_state=42, scoring='neg_mean_squared_error')

In [100]:
cvres = rnd_search.cv_results_
for mean_score, params in zip(cvres["mean_test_score"], cvres["params"]):
    print(np.sqrt(-mean_score), params)

0.649747445545318 {'max_features': 7, 'n_estimators': 180}
0.6684175349621911 {'max_features': 5, 'n_estimators': 15}
0.6526371941474326 {'max_features': 3, 'n_estimators': 72}
0.6611237970609892 {'max_features': 5, 'n_estimators': 21}
0.6514682634658422 {'max_features': 7, 'n_estimators': 122}
0.6524678914365252 {'max_features': 3, 'n_estimators': 75}
0.6499517863414168 {'max_features': 3, 'n_estimators': 88}
0.646994882467297 {'max_features': 5, 'n_estimators': 100}
0.6484061788029608 {'max_features': 3, 'n_estimators': 150}
0.7840628828301816 {'max_features': 5, 'n_estimators': 2}

-> max_features: 5, n_estimators: 100일 때 최적의 솔루션!

In [101]:
feature_importances = grid_search.best_estimator_.feature_importances_
feature_importances

array([0.07247647, 0.11846529, 0.07964725, 0.06128697, 0.0709174 ,
       0.05786914, 0.08603373, 0.10258253, 0.06278581, 0.12671631,
       0.16121909])

# Random Forest

In [102]:
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor(n_estimators=100, max_features=5, random_state=42)
forest_reg.fit(wine_data, wine_quality)

RandomForestRegressor(max_features=5, random_state=42)

In [103]:
wine_predictions = forest_reg.predict(wine_data)
forest_mse = mean_squared_error(wine_quality, wine_predictions)
forest_rmse = np.sqrt(forest_mse)
forest_rmse

0.20801242325915018

In [104]:
from sklearn.model_selection import cross_val_score

forest_scores = cross_val_score(forest_reg, wine_1, wine_quality,
                                scoring="neg_mean_squared_error", cv=10)
forest_rmse_scores = np.sqrt(-forest_scores)
display_scores(forest_rmse_scores)

Scores: [0.62768573 0.59913062 0.68502555 0.65573241 0.57155872 0.72667522
 0.67086977 0.66187801 0.61156561 0.68914038]
Mean: 0.6499262031794883
Standard deviation: 0.04468013497713338