# ML miniproject #1

* EMNIST 데이터셋의 손글씨 숫자 이미지 분류

In [2]:
import pandas as pd
import numpy as np

emnist = pd.read_csv('emnist-digits-train.csv')

In [3]:
emnist.head()

,8,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.511,0.512,0.513,0.514,0.515,0.516,0.517,0.518,0.519,0.520
0,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
X = emnist.drop(['8'], axis=1) # 타겟 레이블을 제외한 데이터
X

,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,...,0.511,0.512,0.513,0.514,0.515,0.516,0.517,0.518,0.519,0.520
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
239995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
239996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
239997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
239998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
y = emnist['8'] # 타겟 레이블
y

0         9
1         6
2         3
3         6
4         6
         ..
239994    4
239995    2
239996    1
239997    1
239998    0
Name: 8, Length: 239999, dtype: int64


# RandomForest

In [6]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)

In [7]:
model.fit(X, y)

RandomForestClassifier(random_state=42)

In [8]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=10, scoring="accuracy")

In [11]:
scores

array([0.98133333, 0.98033333, 0.98145833, 0.98083333, 0.98025   ,
       0.982     , 0.982     , 0.98104167, 0.98016667, 0.98112421])

In [12]:
scores.mean() # 정확도 교차검증 평균

0.9810540880175562